# Generated by Django 4.1 on 2022-08-24 22:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_account_uuid_alter_account_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="uuid",
        ),
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, primary_key=True, serialize=False
            ),
        ),
    ]
